version: '2.2'

services:
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: employeeportal 
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      springboot-mysql-net:
     

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
    environment:  
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeeportal
      - spring.datasource.username=oumayma
      - spring.datasource.password=jellali@OUMAYMA
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      - springboot-mysql-net
    restart: always

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ../my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - springboot-mysql-net
    restart: always  

networks:
  springboot-mysql-net:
